name: Java CI with Gradle

on:
  push:
    branches: ["ci-testing"]
    tags:
      - '**'

jobs:
  build:
    name: Build Gradle Project
    runs-on: self-hosted
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle and JaCoCo
        run: ./gradlew jacocoTestReport

      - name: Upload the generated JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: '**/build/reports/jacoco/test/html/index.html'

      - name: Upload the generated Gradle test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/build/reports/tests/'

      - name: Generate Checkstyle Reports
        run: ./gradlew check

      - name: Upload the generated Checkstyle reports as annotations
        uses: lcollins/checkstyle-github-action@v2
        with:
          path: '**/build/reports/checkstyle/*.xml'

  distribute:
    name: Package and Distribute the Desktop JAR
    needs: build
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Package with Gradle
        run: ./gradlew :desktop:dist

      - name: Upload the JAR artifact
        uses: softprops/action-gh-release@v2
        with:
          files: desktop/build/libs/desktop.jar
