name: Java CI with Gradle

on:
  push:
    branches: ["ci-testing"]
  pull_request:
    branches: ["ci-testing"]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build jacocoTestReport
