name: Java CI with Gradle

on:
  pull_request:

jobs:
  build:
    name: Test Gradle Project for PR
    runs-on: self-hosted
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate the Test Coverage Report
        run: ${{ github.workspace }}/gradlew jacocoTestReport

      - name: Attach the report to the PR
        uses: Vadgyik/jacoco-report@master
        with:
          title: Coverage Report
          update-comment: true
          paths:
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
